server:
  port: 8900
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/, http://peer-1-server.com:9001/eureka/, http://peer-2-server.com:9002/eureka/ #, http://peer-3-server.com:9003/eureka/